const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
const SET_PRODUCTS = 'SET_PRODUCTS'
const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS'

export {
    FETCH_PRODUCTS,
    SET_PRODUCTS,
    ADD_PRODUCT_CART,
    SET_FILTERED_PRODUCTS
}